# Generated by Django 4.2.7 on 2023-11-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default.jpg", upload_to="static/profile_pics"
            ),
        ),
    ]
