# Generated by Django 4.2.7 on 2023-11-14 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Home", "0006_alter_userprofile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMoods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anger", models.IntegerField()),
                ("disgust", models.IntegerField()),
                ("fear", models.IntegerField()),
                ("neutral", models.IntegerField()),
                ("happiness", models.IntegerField()),
                ("sadness", models.IntegerField()),
                ("surprise", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "usermoods",},
        ),
    ]
