# Generated by Django 4.2.7 on 2023-11-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0007_usermoods"),
    ]

    operations = [
        migrations.RemoveField(model_name="usermoods", name="anger",),
        migrations.RemoveField(model_name="usermoods", name="disgust",),
        migrations.RemoveField(model_name="usermoods", name="fear",),
        migrations.RemoveField(model_name="usermoods", name="happiness",),
        migrations.RemoveField(model_name="usermoods", name="neutral",),
        migrations.RemoveField(model_name="usermoods", name="sadness",),
        migrations.RemoveField(model_name="usermoods", name="surprise",),
        migrations.AddField(
            model_name="usermoods",
            name="recent_mood",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
