# Generated by Django 4.2.7 on 2024-03-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0008_remove_usermoods_anger_remove_usermoods_disgust_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Image Entry",
                "verbose_name_plural": "Image Entries",
            },
        ),
    ]
