# Generated by Django 4.2.7 on 2024-05-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0011_journalcounter_imageentry_journal_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageentry",
            name="journal_counter",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
