# Generated by Django 4.2.7 on 2024-05-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0013_imageentry_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermoods",
            name="secondary_mood",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
