# Generated by Django 4.2.7 on 2024-05-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0014_usermoods_secondary_mood"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermoods",
            name="image_mood",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
